name: Create Release and Push to Marketplace
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        generateReleaseNotes: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}