name: Create Release and Push to Marketplace
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
    - name: Tag commit
      run: |
        git config --local user.email "james@jcdc.dev"
        git config --local user.name "James"
        git tag -a $GitVersion_SemVer -m "Release $GitVersion_SemVer"
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        generateReleaseNotes: true
        tag: $GitVersion_SemVer
        allowUpdates: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        tags: true
